config/routes.rb
PointsOfInterest::Application.routes.draw do
  root to: "places#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :places, path: 'lugares'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :place
  attr_accessible :directory, :place_id

  validates :directory, :place, :presence => true

  mount_uploader :directory, PlacePictureUploader
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :address, :description, :latitude, :longitude, :name

  has_many :pictures
  validates :name, :address, :description, :presence => true

  geocoded_by :address

  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    first = Picture.order("RANDOM()").first
    if first.nil?
      @index_image = ActionController::Base.helpers.asset_path("padrao.png")
    else
      @index_image = first.directory_url
    end
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PointsOfInterest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<div class="logo clearfix">
	<div class="index_picture">
        <%= link_to root_path, title: "Ir para a homepage" do %>
          <%= image_tag(@index_image)%>
        <% end %>
	</div>
    <div class="index_description">
      <h1>Lugares</h1>
      <p>Aqui pode ir uma descrição para falar sobre o site</p>
    </div>
</div>
<div class="places clearfix">
  <% @places.each do |place| %>
    <div class="place">
      <div class="content">
		<div class="picture">
          <%= link_to place do %>
            <%= image_tag(place.pictures.first.directory_url)%>
          <% end %>
		</div>
        <p class="place_name"><%= link_to place.name, place_path(place) %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="logo clearfix">
	<div class="point_image">
      <%= link_to root_path, title: "Ir para a homepage" do %>
        <%= image_tag(@place.pictures.order("RANDOM()").first.directory_url) %>
      <% end %>
	</div>
      <div class="show_description">
        <h1><%= @place.name %></h1>
      </div>
</div>
<div>
  <p>
    <strong>Endereço: </strong>
    <%= @place.address.titleize %>
  </p>
  <p>Descrição:</p>
  <%= simple_format @place.description %>
  <% if @place.latitude.present? %>
    Pode exibir o mapa, em <%= @place.latitude %>,<%= @place.longitude %>
  <% end %>
  <% @place.pictures.each do |picture| %>
    <div>
      <%= image_tag picture.directory_url, alt: @place.name %>
    </div>
  <% end %>
</div>